[build]
    command = "echo 'No build required'"
    publish = "/"
    functions = "functions"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[[redirects]]
    from = "/login"
    to = "/login.html"

[[redirects]]
    from = "/register"
    to = "/register.html"
    status = 200

[[redirects]]
    from = "/admin"
    to = "/admin.html"
    status = 200

[[redirects]]
    from = "/post"
    to = "/post.html"
    status = 200
