[build]
  publish = "public"
  functions = "functions"
  command = "npm install"
  node_bundler = "esbuild"

[functions]
  node_bundler = "esbuild"
  node_version = "18"
  directory = "functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
