[build]
    command = "echo 'No build required'"
    publish = "/"
    functions = "functions"
    environment = { NODE_VERSION = "18" }

[functions]
    node_bundler = "esbuild"
    [[functions.schedules]]
        name = "daily-maintenance"
        description = "Daily server maintenance"
        schedule = "0 0 * * *" # နေ့စဉ် ည 12:00 (UTC) တွင် အလုပ်လုပ်မည်
        to = "/.netlify/functions/data?reset=true"
